# Frequency domain convolution (using fft)

In [33]:
import sys
import numpy as np
from scipy import signal 
from scipy import linalg 

## 1D convolution (frequency domain)

In [34]:
x = [1, 2, 3, -2, 5, 6]
x = np.array(x)
h = [2, -1, 1, 4]
h = np.array(h)

n1 = len(x)
n2 = len(h)
N = n1 + n2 - 1

zpx = np.append(x, [0]*(N-n1))
print("Zero-padded x(n): ")
print(zpx)

zph = np.append(h, [0]*(N-n2))
print("Zero padded h(n): ")
print(zph)

X = np.fft.fft(zpx)
H = np.fft.fft(zph)

y = np.fft.ifft(X * H).real

print("Convolution of x(n) and h(n): ")
print("y(n) = ")
print(y)

Zero-padded x(n): 
[ 1  2  3 -2  5  6  0  0  0]
Zero padded h(n): 
[ 2 -1  1  4  0  0  0  0  0]
Convolution of x(n) and h(n): 
y(n) = 
[ 2.  3.  5. -1. 23. 17. -9. 26. 24.]


In [35]:
print('Scipy convolve function: ')    # señal para comparar resultados
print(signal.convolve(x, h))

Scipy convolve function: 
[ 2  3  5 -1 23 17 -9 26 24]


## 2D convolution (frequency domain)

In [36]:
x = [[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, 3, 0], [0, 0, 0, 1]]
x = np.array(x)

h = [[4, 5], [3, 4]]
h = np.array(h)

In [37]:
print('input x: ')
print(x)

print('kernel h: ')
print(h)

input x: 
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0  3  0]
 [ 0  0  0  1]]
kernel h: 
[[4 5]
 [3 4]]


In [38]:
print('conv: ')
print(signal.convolve2d(x, h), 'full')

conv: 
[[ 4  5  0  0  0]
 [ 3  0 -5  0  0]
 [ 0 -3  8 15  0]
 [ 0  0  9 16  5]
 [ 0  0  0  3  4]] full


In [39]:
s1 = np.array(x.shape)
s2 = np.array(h.shape)

size = s1 + s2 - 1

fsize = 2 ** np.ceil(np.log2(size)).astype(int)
fslice = tuple([slice(0, int(sz)) for sz in size])

fslice

(slice(0, 5, None), slice(0, 5, None))

In [40]:
new_x = np.fft.fft2(x, fsize)
new_h = np.fft.fft2(h, fsize)
result = np.fft.ifft2(new_x*new_h)[fslice].copy()

print(result)

[[ 4.00000000e+00+0.00000000e+00j  5.00000000e+00+1.33805644e-17j
   0.00000000e+00+0.00000000e+00j  6.66133815e-16+2.04873146e-17j
   0.00000000e+00+0.00000000e+00j]
 [ 3.00000000e+00+1.52198045e-17j  2.12520397e-16+4.06470994e-18j
  -5.00000000e+00+1.57218686e-18j -3.14018492e-16-7.70793580e-17j
   4.44089210e-16+0.00000000e+00j]
 [ 4.44089210e-16+0.00000000e+00j -3.00000000e+00-6.91250830e-18j
   8.00000000e+00+0.00000000e+00j  1.50000000e+01-2.01557290e-16j
   0.00000000e+00+0.00000000e+00j]
 [ 4.44089210e-16+0.00000000e+00j -1.01498095e-16+4.06470994e-18j
   9.00000000e+00-1.87208859e-17j  1.60000000e+01-5.48463803e-16j
   5.00000000e+00-2.53663409e-17j]
 [ 2.22044605e-16+0.00000000e+00j  0.00000000e+00+1.33805644e-17j
   0.00000000e+00+0.00000000e+00j  3.00000000e+00+2.04873146e-17j
   4.00000000e+00+0.00000000e+00j]]


In [41]:
print('fft for my method: ')
print(np.array(result.real, np.int32))

fft for my method: 
[[ 4  5  0  0  0]
 [ 2  0 -5  0  0]
 [ 0 -3  8 15  0]
 [ 0  0  9 16  5]
 [ 0  0  0  2  4]]


In [42]:
print('fft convolution: ')
print(np.array(signal.fftconvolve(x, h), np.int32))

fft convolution: 
[[ 4  5  0  0  0]
 [ 3  0 -4  0  0]
 [ 0 -2  8 15  0]
 [ 0  0  9 15  4]
 [ 0  0  0  3  4]]
